package cm.cn.po;

import java.util.Date;

public class Gpsinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.gpsId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Integer gpsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.createDate
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.deleted
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.owner
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.remark
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.tenantId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Integer tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.alarmState
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Integer alarmstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.altitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Double altitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.commandId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Integer commandid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.direction
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Integer direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.gas
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Double gas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.latitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.location
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.longitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.mileage
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Double mileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.plateNo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private String plateno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.recordVelocity
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Double recordvelocity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.runStatus
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private String runstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.sendTime
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.simNo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private String simno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.status
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.valid
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.velocity
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Double velocity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpsinfo.signal_v
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    private Integer signalV;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.gpsId
     *
     * @return the value of gpsinfo.gpsId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Integer getGpsid() {
        return gpsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.gpsId
     *
     * @param gpsid the value for gpsinfo.gpsId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setGpsid(Integer gpsid) {
        this.gpsid = gpsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.createDate
     *
     * @return the value of gpsinfo.createDate
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.createDate
     *
     * @param createdate the value for gpsinfo.createDate
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.deleted
     *
     * @return the value of gpsinfo.deleted
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.deleted
     *
     * @param deleted the value for gpsinfo.deleted
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.owner
     *
     * @return the value of gpsinfo.owner
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.owner
     *
     * @param owner the value for gpsinfo.owner
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.remark
     *
     * @return the value of gpsinfo.remark
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.remark
     *
     * @param remark the value for gpsinfo.remark
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.tenantId
     *
     * @return the value of gpsinfo.tenantId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Integer getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.tenantId
     *
     * @param tenantid the value for gpsinfo.tenantId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setTenantid(Integer tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.alarmState
     *
     * @return the value of gpsinfo.alarmState
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Integer getAlarmstate() {
        return alarmstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.alarmState
     *
     * @param alarmstate the value for gpsinfo.alarmState
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setAlarmstate(Integer alarmstate) {
        this.alarmstate = alarmstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.altitude
     *
     * @return the value of gpsinfo.altitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Double getAltitude() {
        return altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.altitude
     *
     * @param altitude the value for gpsinfo.altitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setAltitude(Double altitude) {
        this.altitude = altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.commandId
     *
     * @return the value of gpsinfo.commandId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Integer getCommandid() {
        return commandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.commandId
     *
     * @param commandid the value for gpsinfo.commandId
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setCommandid(Integer commandid) {
        this.commandid = commandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.direction
     *
     * @return the value of gpsinfo.direction
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Integer getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.direction
     *
     * @param direction the value for gpsinfo.direction
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.gas
     *
     * @return the value of gpsinfo.gas
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Double getGas() {
        return gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.gas
     *
     * @param gas the value for gpsinfo.gas
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setGas(Double gas) {
        this.gas = gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.latitude
     *
     * @return the value of gpsinfo.latitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.latitude
     *
     * @param latitude the value for gpsinfo.latitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.location
     *
     * @return the value of gpsinfo.location
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.location
     *
     * @param location the value for gpsinfo.location
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.longitude
     *
     * @return the value of gpsinfo.longitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.longitude
     *
     * @param longitude the value for gpsinfo.longitude
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.mileage
     *
     * @return the value of gpsinfo.mileage
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Double getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.mileage
     *
     * @param mileage the value for gpsinfo.mileage
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setMileage(Double mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.plateNo
     *
     * @return the value of gpsinfo.plateNo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public String getPlateno() {
        return plateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.plateNo
     *
     * @param plateno the value for gpsinfo.plateNo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setPlateno(String plateno) {
        this.plateno = plateno == null ? null : plateno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.recordVelocity
     *
     * @return the value of gpsinfo.recordVelocity
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Double getRecordvelocity() {
        return recordvelocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.recordVelocity
     *
     * @param recordvelocity the value for gpsinfo.recordVelocity
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setRecordvelocity(Double recordvelocity) {
        this.recordvelocity = recordvelocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.runStatus
     *
     * @return the value of gpsinfo.runStatus
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public String getRunstatus() {
        return runstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.runStatus
     *
     * @param runstatus the value for gpsinfo.runStatus
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setRunstatus(String runstatus) {
        this.runstatus = runstatus == null ? null : runstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.sendTime
     *
     * @return the value of gpsinfo.sendTime
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.sendTime
     *
     * @param sendtime the value for gpsinfo.sendTime
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.simNo
     *
     * @return the value of gpsinfo.simNo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public String getSimno() {
        return simno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.simNo
     *
     * @param simno the value for gpsinfo.simNo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setSimno(String simno) {
        this.simno = simno == null ? null : simno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.status
     *
     * @return the value of gpsinfo.status
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.status
     *
     * @param status the value for gpsinfo.status
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.valid
     *
     * @return the value of gpsinfo.valid
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.valid
     *
     * @param valid the value for gpsinfo.valid
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.velocity
     *
     * @return the value of gpsinfo.velocity
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Double getVelocity() {
        return velocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.velocity
     *
     * @param velocity the value for gpsinfo.velocity
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setVelocity(Double velocity) {
        this.velocity = velocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpsinfo.signal_v
     *
     * @return the value of gpsinfo.signal_v
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public Integer getSignalV() {
        return signalV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpsinfo.signal_v
     *
     * @param signalV the value for gpsinfo.signal_v
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    public void setSignalV(Integer signalV) {
        this.signalV = signalV;
    }
}