package cm.cn.po;

import java.util.Date;

public class HlCheckWaybill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.id
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.checkCar_array
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String checkcarArray;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.driverlog_array
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String driverlogArray;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.waybill_id
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Integer waybillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.waybill_state
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String waybillState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.driver_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String driverConfirmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.driver_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Date driverConfirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.driver_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String driverSignatureStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.driver_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Date driverSignatureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.driver_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String driverSignaturePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.safer_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String saferConfirmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.safer_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Date saferConfirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.safer_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String saferSignatureStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.safer_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Date saferSignatureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.safer_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String saferSignaturePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.manufacturer_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String manufacturerConfirmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.manufacturer_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Date manufacturerConfirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.manufacturer_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String manufacturerSignatureStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.manufacturer_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Date manufacturerSignatureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.manufacturer_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String manufacturerSignaturePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.consignee_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String consigneeConfirmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.consignee_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Date consigneeConfirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.consignee_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String consigneeSignatureStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.consignee_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private Date consigneeSignatureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.consignee_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    private String consigneeSignaturePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.id
     *
     * @return the value of hl_check_waybill.id
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.id
     *
     * @param id the value for hl_check_waybill.id
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.checkCar_array
     *
     * @return the value of hl_check_waybill.checkCar_array
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getCheckcarArray() {
        return checkcarArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.checkCar_array
     *
     * @param checkcarArray the value for hl_check_waybill.checkCar_array
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setCheckcarArray(String checkcarArray) {
        this.checkcarArray = checkcarArray == null ? null : checkcarArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.driverlog_array
     *
     * @return the value of hl_check_waybill.driverlog_array
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getDriverlogArray() {
        return driverlogArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.driverlog_array
     *
     * @param driverlogArray the value for hl_check_waybill.driverlog_array
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setDriverlogArray(String driverlogArray) {
        this.driverlogArray = driverlogArray == null ? null : driverlogArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.waybill_id
     *
     * @return the value of hl_check_waybill.waybill_id
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Integer getWaybillId() {
        return waybillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.waybill_id
     *
     * @param waybillId the value for hl_check_waybill.waybill_id
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setWaybillId(Integer waybillId) {
        this.waybillId = waybillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.waybill_state
     *
     * @return the value of hl_check_waybill.waybill_state
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getWaybillState() {
        return waybillState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.waybill_state
     *
     * @param waybillState the value for hl_check_waybill.waybill_state
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setWaybillState(String waybillState) {
        this.waybillState = waybillState == null ? null : waybillState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.driver_confirm_status
     *
     * @return the value of hl_check_waybill.driver_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getDriverConfirmStatus() {
        return driverConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.driver_confirm_status
     *
     * @param driverConfirmStatus the value for hl_check_waybill.driver_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setDriverConfirmStatus(String driverConfirmStatus) {
        this.driverConfirmStatus = driverConfirmStatus == null ? null : driverConfirmStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.driver_confirm_time
     *
     * @return the value of hl_check_waybill.driver_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Date getDriverConfirmTime() {
        return driverConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.driver_confirm_time
     *
     * @param driverConfirmTime the value for hl_check_waybill.driver_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setDriverConfirmTime(Date driverConfirmTime) {
        this.driverConfirmTime = driverConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.driver_signature_status
     *
     * @return the value of hl_check_waybill.driver_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getDriverSignatureStatus() {
        return driverSignatureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.driver_signature_status
     *
     * @param driverSignatureStatus the value for hl_check_waybill.driver_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setDriverSignatureStatus(String driverSignatureStatus) {
        this.driverSignatureStatus = driverSignatureStatus == null ? null : driverSignatureStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.driver_signature_time
     *
     * @return the value of hl_check_waybill.driver_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Date getDriverSignatureTime() {
        return driverSignatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.driver_signature_time
     *
     * @param driverSignatureTime the value for hl_check_waybill.driver_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setDriverSignatureTime(Date driverSignatureTime) {
        this.driverSignatureTime = driverSignatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.driver_signature_path
     *
     * @return the value of hl_check_waybill.driver_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getDriverSignaturePath() {
        return driverSignaturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.driver_signature_path
     *
     * @param driverSignaturePath the value for hl_check_waybill.driver_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setDriverSignaturePath(String driverSignaturePath) {
        this.driverSignaturePath = driverSignaturePath == null ? null : driverSignaturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.safer_confirm_status
     *
     * @return the value of hl_check_waybill.safer_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getSaferConfirmStatus() {
        return saferConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.safer_confirm_status
     *
     * @param saferConfirmStatus the value for hl_check_waybill.safer_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setSaferConfirmStatus(String saferConfirmStatus) {
        this.saferConfirmStatus = saferConfirmStatus == null ? null : saferConfirmStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.safer_confirm_time
     *
     * @return the value of hl_check_waybill.safer_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Date getSaferConfirmTime() {
        return saferConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.safer_confirm_time
     *
     * @param saferConfirmTime the value for hl_check_waybill.safer_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setSaferConfirmTime(Date saferConfirmTime) {
        this.saferConfirmTime = saferConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.safer_signature_status
     *
     * @return the value of hl_check_waybill.safer_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getSaferSignatureStatus() {
        return saferSignatureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.safer_signature_status
     *
     * @param saferSignatureStatus the value for hl_check_waybill.safer_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setSaferSignatureStatus(String saferSignatureStatus) {
        this.saferSignatureStatus = saferSignatureStatus == null ? null : saferSignatureStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.safer_signature_time
     *
     * @return the value of hl_check_waybill.safer_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Date getSaferSignatureTime() {
        return saferSignatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.safer_signature_time
     *
     * @param saferSignatureTime the value for hl_check_waybill.safer_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setSaferSignatureTime(Date saferSignatureTime) {
        this.saferSignatureTime = saferSignatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.safer_signature_path
     *
     * @return the value of hl_check_waybill.safer_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getSaferSignaturePath() {
        return saferSignaturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.safer_signature_path
     *
     * @param saferSignaturePath the value for hl_check_waybill.safer_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setSaferSignaturePath(String saferSignaturePath) {
        this.saferSignaturePath = saferSignaturePath == null ? null : saferSignaturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.manufacturer_confirm_status
     *
     * @return the value of hl_check_waybill.manufacturer_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getManufacturerConfirmStatus() {
        return manufacturerConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.manufacturer_confirm_status
     *
     * @param manufacturerConfirmStatus the value for hl_check_waybill.manufacturer_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setManufacturerConfirmStatus(String manufacturerConfirmStatus) {
        this.manufacturerConfirmStatus = manufacturerConfirmStatus == null ? null : manufacturerConfirmStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.manufacturer_confirm_time
     *
     * @return the value of hl_check_waybill.manufacturer_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Date getManufacturerConfirmTime() {
        return manufacturerConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.manufacturer_confirm_time
     *
     * @param manufacturerConfirmTime the value for hl_check_waybill.manufacturer_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setManufacturerConfirmTime(Date manufacturerConfirmTime) {
        this.manufacturerConfirmTime = manufacturerConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.manufacturer_signature_status
     *
     * @return the value of hl_check_waybill.manufacturer_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getManufacturerSignatureStatus() {
        return manufacturerSignatureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.manufacturer_signature_status
     *
     * @param manufacturerSignatureStatus the value for hl_check_waybill.manufacturer_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setManufacturerSignatureStatus(String manufacturerSignatureStatus) {
        this.manufacturerSignatureStatus = manufacturerSignatureStatus == null ? null : manufacturerSignatureStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.manufacturer_signature_time
     *
     * @return the value of hl_check_waybill.manufacturer_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Date getManufacturerSignatureTime() {
        return manufacturerSignatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.manufacturer_signature_time
     *
     * @param manufacturerSignatureTime the value for hl_check_waybill.manufacturer_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setManufacturerSignatureTime(Date manufacturerSignatureTime) {
        this.manufacturerSignatureTime = manufacturerSignatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.manufacturer_signature_path
     *
     * @return the value of hl_check_waybill.manufacturer_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getManufacturerSignaturePath() {
        return manufacturerSignaturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.manufacturer_signature_path
     *
     * @param manufacturerSignaturePath the value for hl_check_waybill.manufacturer_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setManufacturerSignaturePath(String manufacturerSignaturePath) {
        this.manufacturerSignaturePath = manufacturerSignaturePath == null ? null : manufacturerSignaturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.consignee_confirm_status
     *
     * @return the value of hl_check_waybill.consignee_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getConsigneeConfirmStatus() {
        return consigneeConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.consignee_confirm_status
     *
     * @param consigneeConfirmStatus the value for hl_check_waybill.consignee_confirm_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setConsigneeConfirmStatus(String consigneeConfirmStatus) {
        this.consigneeConfirmStatus = consigneeConfirmStatus == null ? null : consigneeConfirmStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.consignee_confirm_time
     *
     * @return the value of hl_check_waybill.consignee_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Date getConsigneeConfirmTime() {
        return consigneeConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.consignee_confirm_time
     *
     * @param consigneeConfirmTime the value for hl_check_waybill.consignee_confirm_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setConsigneeConfirmTime(Date consigneeConfirmTime) {
        this.consigneeConfirmTime = consigneeConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.consignee_signature_status
     *
     * @return the value of hl_check_waybill.consignee_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getConsigneeSignatureStatus() {
        return consigneeSignatureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.consignee_signature_status
     *
     * @param consigneeSignatureStatus the value for hl_check_waybill.consignee_signature_status
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setConsigneeSignatureStatus(String consigneeSignatureStatus) {
        this.consigneeSignatureStatus = consigneeSignatureStatus == null ? null : consigneeSignatureStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.consignee_signature_time
     *
     * @return the value of hl_check_waybill.consignee_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public Date getConsigneeSignatureTime() {
        return consigneeSignatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.consignee_signature_time
     *
     * @param consigneeSignatureTime the value for hl_check_waybill.consignee_signature_time
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setConsigneeSignatureTime(Date consigneeSignatureTime) {
        this.consigneeSignatureTime = consigneeSignatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.consignee_signature_path
     *
     * @return the value of hl_check_waybill.consignee_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public String getConsigneeSignaturePath() {
        return consigneeSignaturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.consignee_signature_path
     *
     * @param consigneeSignaturePath the value for hl_check_waybill.consignee_signature_path
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    public void setConsigneeSignaturePath(String consigneeSignaturePath) {
        this.consigneeSignaturePath = consigneeSignaturePath == null ? null : consigneeSignaturePath.trim();
    }
}