package cm.cn.po;

import java.util.Date;

public class HlMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.send_time
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.send_way
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private String sendWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.receiver
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.receiver_id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private Integer receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.receiver_contact
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private String receiverContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.sender
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.sender_id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private Integer senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_message.remark
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.id
     *
     * @return the value of hl_message.id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.id
     *
     * @param id the value for hl_message.id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.send_time
     *
     * @return the value of hl_message.send_time
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.send_time
     *
     * @param sendTime the value for hl_message.send_time
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.send_way
     *
     * @return the value of hl_message.send_way
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public String getSendWay() {
        return sendWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.send_way
     *
     * @param sendWay the value for hl_message.send_way
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setSendWay(String sendWay) {
        this.sendWay = sendWay == null ? null : sendWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.message
     *
     * @return the value of hl_message.message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.message
     *
     * @param message the value for hl_message.message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.receiver
     *
     * @return the value of hl_message.receiver
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.receiver
     *
     * @param receiver the value for hl_message.receiver
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.receiver_id
     *
     * @return the value of hl_message.receiver_id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.receiver_id
     *
     * @param receiverId the value for hl_message.receiver_id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.receiver_contact
     *
     * @return the value of hl_message.receiver_contact
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public String getReceiverContact() {
        return receiverContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.receiver_contact
     *
     * @param receiverContact the value for hl_message.receiver_contact
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setReceiverContact(String receiverContact) {
        this.receiverContact = receiverContact == null ? null : receiverContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.sender
     *
     * @return the value of hl_message.sender
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.sender
     *
     * @param sender the value for hl_message.sender
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.sender_id
     *
     * @return the value of hl_message.sender_id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.sender_id
     *
     * @param senderId the value for hl_message.sender_id
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_message.remark
     *
     * @return the value of hl_message.remark
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_message.remark
     *
     * @param remark the value for hl_message.remark
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}