package cm.cn.po;

import java.util.Date;

public class HlSite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.id
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.site_name
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.type
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.company_id
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.province
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.city
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.district
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.address
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.linkman
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.linkman_phone
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String linkmanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.linkman_photo_path
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String linkmanPhotoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.code
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.checktime
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.create_time
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.update_time
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.status
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_site.remark
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.id
     *
     * @return the value of hl_site.id
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.id
     *
     * @param id the value for hl_site.id
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.site_name
     *
     * @return the value of hl_site.site_name
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.site_name
     *
     * @param siteName the value for hl_site.site_name
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.type
     *
     * @return the value of hl_site.type
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.type
     *
     * @param type the value for hl_site.type
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.company_id
     *
     * @return the value of hl_site.company_id
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.company_id
     *
     * @param companyId the value for hl_site.company_id
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.province
     *
     * @return the value of hl_site.province
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.province
     *
     * @param province the value for hl_site.province
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.city
     *
     * @return the value of hl_site.city
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.city
     *
     * @param city the value for hl_site.city
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.district
     *
     * @return the value of hl_site.district
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.district
     *
     * @param district the value for hl_site.district
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.address
     *
     * @return the value of hl_site.address
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.address
     *
     * @param address the value for hl_site.address
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.linkman
     *
     * @return the value of hl_site.linkman
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.linkman
     *
     * @param linkman the value for hl_site.linkman
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.linkman_phone
     *
     * @return the value of hl_site.linkman_phone
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getLinkmanPhone() {
        return linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.linkman_phone
     *
     * @param linkmanPhone the value for hl_site.linkman_phone
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setLinkmanPhone(String linkmanPhone) {
        this.linkmanPhone = linkmanPhone == null ? null : linkmanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.linkman_photo_path
     *
     * @return the value of hl_site.linkman_photo_path
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getLinkmanPhotoPath() {
        return linkmanPhotoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.linkman_photo_path
     *
     * @param linkmanPhotoPath the value for hl_site.linkman_photo_path
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setLinkmanPhotoPath(String linkmanPhotoPath) {
        this.linkmanPhotoPath = linkmanPhotoPath == null ? null : linkmanPhotoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.code
     *
     * @return the value of hl_site.code
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.code
     *
     * @param code the value for hl_site.code
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.checktime
     *
     * @return the value of hl_site.checktime
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.checktime
     *
     * @param checktime the value for hl_site.checktime
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime == null ? null : checktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.create_time
     *
     * @return the value of hl_site.create_time
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.create_time
     *
     * @param createTime the value for hl_site.create_time
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.update_time
     *
     * @return the value of hl_site.update_time
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.update_time
     *
     * @param updateTime the value for hl_site.update_time
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.status
     *
     * @return the value of hl_site.status
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.status
     *
     * @param status the value for hl_site.status
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_site.remark
     *
     * @return the value of hl_site.remark
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_site.remark
     *
     * @param remark the value for hl_site.remark
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}