package cm.cn.po;

import java.util.Date;

public class HlWaybillSite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill_site.id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill_site.waybill_id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    private Integer waybillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill_site.site_id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill_site.create_time
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill_site.update_time
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill_site.id
     *
     * @return the value of hl_waybill_site.id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill_site.id
     *
     * @param id the value for hl_waybill_site.id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill_site.waybill_id
     *
     * @return the value of hl_waybill_site.waybill_id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public Integer getWaybillId() {
        return waybillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill_site.waybill_id
     *
     * @param waybillId the value for hl_waybill_site.waybill_id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public void setWaybillId(Integer waybillId) {
        this.waybillId = waybillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill_site.site_id
     *
     * @return the value of hl_waybill_site.site_id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill_site.site_id
     *
     * @param siteId the value for hl_waybill_site.site_id
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill_site.create_time
     *
     * @return the value of hl_waybill_site.create_time
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill_site.create_time
     *
     * @param createTime the value for hl_waybill_site.create_time
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill_site.update_time
     *
     * @return the value of hl_waybill_site.update_time
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill_site.update_time
     *
     * @param updateTime the value for hl_waybill_site.update_time
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}