package cm.cn.po;

import java.util.Date;

public class HlWaybill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.consign_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Date consignDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.loading_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Date loadingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.upload_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Date uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.company_id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.goods_name
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.goods_id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.nation_code
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private String nationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.code
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.total
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.weight
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.volume
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Double volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.freight
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Double freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.car_num
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private String carNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.reserve_one
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.reserve_two
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.reserve_three
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.waybill_state
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Integer waybillState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.create_time
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.update_time
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.id
     *
     * @return the value of hl_waybill.id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.id
     *
     * @param id the value for hl_waybill.id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.consign_date
     *
     * @return the value of hl_waybill.consign_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Date getConsignDate() {
        return consignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.consign_date
     *
     * @param consignDate the value for hl_waybill.consign_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setConsignDate(Date consignDate) {
        this.consignDate = consignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.loading_date
     *
     * @return the value of hl_waybill.loading_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Date getLoadingDate() {
        return loadingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.loading_date
     *
     * @param loadingDate the value for hl_waybill.loading_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setLoadingDate(Date loadingDate) {
        this.loadingDate = loadingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.upload_date
     *
     * @return the value of hl_waybill.upload_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.upload_date
     *
     * @param uploadDate the value for hl_waybill.upload_date
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.company_id
     *
     * @return the value of hl_waybill.company_id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.company_id
     *
     * @param companyId the value for hl_waybill.company_id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.goods_name
     *
     * @return the value of hl_waybill.goods_name
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.goods_name
     *
     * @param goodsName the value for hl_waybill.goods_name
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.goods_id
     *
     * @return the value of hl_waybill.goods_id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.goods_id
     *
     * @param goodsId the value for hl_waybill.goods_id
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.nation_code
     *
     * @return the value of hl_waybill.nation_code
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.nation_code
     *
     * @param nationCode the value for hl_waybill.nation_code
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.code
     *
     * @return the value of hl_waybill.code
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.code
     *
     * @param code the value for hl_waybill.code
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.total
     *
     * @return the value of hl_waybill.total
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.total
     *
     * @param total the value for hl_waybill.total
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.weight
     *
     * @return the value of hl_waybill.weight
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.weight
     *
     * @param weight the value for hl_waybill.weight
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.volume
     *
     * @return the value of hl_waybill.volume
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.volume
     *
     * @param volume the value for hl_waybill.volume
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.freight
     *
     * @return the value of hl_waybill.freight
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Double getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.freight
     *
     * @param freight the value for hl_waybill.freight
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setFreight(Double freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.car_num
     *
     * @return the value of hl_waybill.car_num
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public String getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.car_num
     *
     * @param carNum the value for hl_waybill.car_num
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setCarNum(String carNum) {
        this.carNum = carNum == null ? null : carNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.reserve_one
     *
     * @return the value of hl_waybill.reserve_one
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.reserve_one
     *
     * @param reserveOne the value for hl_waybill.reserve_one
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.reserve_two
     *
     * @return the value of hl_waybill.reserve_two
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.reserve_two
     *
     * @param reserveTwo the value for hl_waybill.reserve_two
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.reserve_three
     *
     * @return the value of hl_waybill.reserve_three
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.reserve_three
     *
     * @param reserveThree the value for hl_waybill.reserve_three
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.waybill_state
     *
     * @return the value of hl_waybill.waybill_state
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Integer getWaybillState() {
        return waybillState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.waybill_state
     *
     * @param waybillState the value for hl_waybill.waybill_state
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setWaybillState(Integer waybillState) {
        this.waybillState = waybillState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.create_time
     *
     * @return the value of hl_waybill.create_time
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.create_time
     *
     * @param createTime the value for hl_waybill.create_time
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.update_time
     *
     * @return the value of hl_waybill.update_time
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.update_time
     *
     * @param updateTime the value for hl_waybill.update_time
     *
     * @mbggenerated Fri Mar 02 14:54:56 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}