package cm.cn.po;

import java.util.Date;

public class HlCarAttach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_car_attach.id
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_car_attach.car_num
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    private String carNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_car_attach.file_name
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_car_attach.file_path
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_car_attach.create_time
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_car_attach.update_time
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_car_attach.id
     *
     * @return the value of hl_car_attach.id
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_car_attach.id
     *
     * @param id the value for hl_car_attach.id
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_car_attach.car_num
     *
     * @return the value of hl_car_attach.car_num
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public String getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_car_attach.car_num
     *
     * @param carNum the value for hl_car_attach.car_num
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public void setCarNum(String carNum) {
        this.carNum = carNum == null ? null : carNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_car_attach.file_name
     *
     * @return the value of hl_car_attach.file_name
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_car_attach.file_name
     *
     * @param fileName the value for hl_car_attach.file_name
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_car_attach.file_path
     *
     * @return the value of hl_car_attach.file_path
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_car_attach.file_path
     *
     * @param filePath the value for hl_car_attach.file_path
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_car_attach.create_time
     *
     * @return the value of hl_car_attach.create_time
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_car_attach.create_time
     *
     * @param createTime the value for hl_car_attach.create_time
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_car_attach.update_time
     *
     * @return the value of hl_car_attach.update_time
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_car_attach.update_time
     *
     * @param updateTime the value for hl_car_attach.update_time
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}