package cm.cn.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HlCheckWaybillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public HlCheckWaybillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayIsNull() {
            addCriterion("checkCar_array is null");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayIsNotNull() {
            addCriterion("checkCar_array is not null");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayEqualTo(String value) {
            addCriterion("checkCar_array =", value, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayNotEqualTo(String value) {
            addCriterion("checkCar_array <>", value, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayGreaterThan(String value) {
            addCriterion("checkCar_array >", value, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayGreaterThanOrEqualTo(String value) {
            addCriterion("checkCar_array >=", value, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayLessThan(String value) {
            addCriterion("checkCar_array <", value, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayLessThanOrEqualTo(String value) {
            addCriterion("checkCar_array <=", value, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayLike(String value) {
            addCriterion("checkCar_array like", value, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayNotLike(String value) {
            addCriterion("checkCar_array not like", value, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayIn(List<String> values) {
            addCriterion("checkCar_array in", values, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayNotIn(List<String> values) {
            addCriterion("checkCar_array not in", values, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayBetween(String value1, String value2) {
            addCriterion("checkCar_array between", value1, value2, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andCheckcarArrayNotBetween(String value1, String value2) {
            addCriterion("checkCar_array not between", value1, value2, "checkcarArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayIsNull() {
            addCriterion("driverlog_array is null");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayIsNotNull() {
            addCriterion("driverlog_array is not null");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayEqualTo(String value) {
            addCriterion("driverlog_array =", value, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayNotEqualTo(String value) {
            addCriterion("driverlog_array <>", value, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayGreaterThan(String value) {
            addCriterion("driverlog_array >", value, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayGreaterThanOrEqualTo(String value) {
            addCriterion("driverlog_array >=", value, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayLessThan(String value) {
            addCriterion("driverlog_array <", value, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayLessThanOrEqualTo(String value) {
            addCriterion("driverlog_array <=", value, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayLike(String value) {
            addCriterion("driverlog_array like", value, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayNotLike(String value) {
            addCriterion("driverlog_array not like", value, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayIn(List<String> values) {
            addCriterion("driverlog_array in", values, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayNotIn(List<String> values) {
            addCriterion("driverlog_array not in", values, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayBetween(String value1, String value2) {
            addCriterion("driverlog_array between", value1, value2, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andDriverlogArrayNotBetween(String value1, String value2) {
            addCriterion("driverlog_array not between", value1, value2, "driverlogArray");
            return (Criteria) this;
        }

        public Criteria andWaybillIdIsNull() {
            addCriterion("waybill_id is null");
            return (Criteria) this;
        }

        public Criteria andWaybillIdIsNotNull() {
            addCriterion("waybill_id is not null");
            return (Criteria) this;
        }

        public Criteria andWaybillIdEqualTo(Integer value) {
            addCriterion("waybill_id =", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotEqualTo(Integer value) {
            addCriterion("waybill_id <>", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdGreaterThan(Integer value) {
            addCriterion("waybill_id >", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("waybill_id >=", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdLessThan(Integer value) {
            addCriterion("waybill_id <", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdLessThanOrEqualTo(Integer value) {
            addCriterion("waybill_id <=", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdIn(List<Integer> values) {
            addCriterion("waybill_id in", values, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotIn(List<Integer> values) {
            addCriterion("waybill_id not in", values, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdBetween(Integer value1, Integer value2) {
            addCriterion("waybill_id between", value1, value2, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotBetween(Integer value1, Integer value2) {
            addCriterion("waybill_id not between", value1, value2, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillStateIsNull() {
            addCriterion("waybill_state is null");
            return (Criteria) this;
        }

        public Criteria andWaybillStateIsNotNull() {
            addCriterion("waybill_state is not null");
            return (Criteria) this;
        }

        public Criteria andWaybillStateEqualTo(String value) {
            addCriterion("waybill_state =", value, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateNotEqualTo(String value) {
            addCriterion("waybill_state <>", value, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateGreaterThan(String value) {
            addCriterion("waybill_state >", value, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateGreaterThanOrEqualTo(String value) {
            addCriterion("waybill_state >=", value, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateLessThan(String value) {
            addCriterion("waybill_state <", value, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateLessThanOrEqualTo(String value) {
            addCriterion("waybill_state <=", value, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateLike(String value) {
            addCriterion("waybill_state like", value, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateNotLike(String value) {
            addCriterion("waybill_state not like", value, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateIn(List<String> values) {
            addCriterion("waybill_state in", values, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateNotIn(List<String> values) {
            addCriterion("waybill_state not in", values, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateBetween(String value1, String value2) {
            addCriterion("waybill_state between", value1, value2, "waybillState");
            return (Criteria) this;
        }

        public Criteria andWaybillStateNotBetween(String value1, String value2) {
            addCriterion("waybill_state not between", value1, value2, "waybillState");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusIsNull() {
            addCriterion("driver_confirm_status is null");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusIsNotNull() {
            addCriterion("driver_confirm_status is not null");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusEqualTo(String value) {
            addCriterion("driver_confirm_status =", value, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusNotEqualTo(String value) {
            addCriterion("driver_confirm_status <>", value, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusGreaterThan(String value) {
            addCriterion("driver_confirm_status >", value, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusGreaterThanOrEqualTo(String value) {
            addCriterion("driver_confirm_status >=", value, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusLessThan(String value) {
            addCriterion("driver_confirm_status <", value, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusLessThanOrEqualTo(String value) {
            addCriterion("driver_confirm_status <=", value, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusLike(String value) {
            addCriterion("driver_confirm_status like", value, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusNotLike(String value) {
            addCriterion("driver_confirm_status not like", value, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusIn(List<String> values) {
            addCriterion("driver_confirm_status in", values, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusNotIn(List<String> values) {
            addCriterion("driver_confirm_status not in", values, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusBetween(String value1, String value2) {
            addCriterion("driver_confirm_status between", value1, value2, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmStatusNotBetween(String value1, String value2) {
            addCriterion("driver_confirm_status not between", value1, value2, "driverConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeIsNull() {
            addCriterion("driver_confirm_time is null");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeIsNotNull() {
            addCriterion("driver_confirm_time is not null");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeEqualTo(Date value) {
            addCriterion("driver_confirm_time =", value, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeNotEqualTo(Date value) {
            addCriterion("driver_confirm_time <>", value, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeGreaterThan(Date value) {
            addCriterion("driver_confirm_time >", value, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("driver_confirm_time >=", value, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeLessThan(Date value) {
            addCriterion("driver_confirm_time <", value, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("driver_confirm_time <=", value, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeIn(List<Date> values) {
            addCriterion("driver_confirm_time in", values, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeNotIn(List<Date> values) {
            addCriterion("driver_confirm_time not in", values, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeBetween(Date value1, Date value2) {
            addCriterion("driver_confirm_time between", value1, value2, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverConfirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("driver_confirm_time not between", value1, value2, "driverConfirmTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusIsNull() {
            addCriterion("driver_signature_status is null");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusIsNotNull() {
            addCriterion("driver_signature_status is not null");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusEqualTo(String value) {
            addCriterion("driver_signature_status =", value, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusNotEqualTo(String value) {
            addCriterion("driver_signature_status <>", value, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusGreaterThan(String value) {
            addCriterion("driver_signature_status >", value, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusGreaterThanOrEqualTo(String value) {
            addCriterion("driver_signature_status >=", value, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusLessThan(String value) {
            addCriterion("driver_signature_status <", value, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusLessThanOrEqualTo(String value) {
            addCriterion("driver_signature_status <=", value, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusLike(String value) {
            addCriterion("driver_signature_status like", value, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusNotLike(String value) {
            addCriterion("driver_signature_status not like", value, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusIn(List<String> values) {
            addCriterion("driver_signature_status in", values, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusNotIn(List<String> values) {
            addCriterion("driver_signature_status not in", values, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusBetween(String value1, String value2) {
            addCriterion("driver_signature_status between", value1, value2, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureStatusNotBetween(String value1, String value2) {
            addCriterion("driver_signature_status not between", value1, value2, "driverSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeIsNull() {
            addCriterion("driver_signature_time is null");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeIsNotNull() {
            addCriterion("driver_signature_time is not null");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeEqualTo(Date value) {
            addCriterion("driver_signature_time =", value, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeNotEqualTo(Date value) {
            addCriterion("driver_signature_time <>", value, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeGreaterThan(Date value) {
            addCriterion("driver_signature_time >", value, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("driver_signature_time >=", value, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeLessThan(Date value) {
            addCriterion("driver_signature_time <", value, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeLessThanOrEqualTo(Date value) {
            addCriterion("driver_signature_time <=", value, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeIn(List<Date> values) {
            addCriterion("driver_signature_time in", values, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeNotIn(List<Date> values) {
            addCriterion("driver_signature_time not in", values, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeBetween(Date value1, Date value2) {
            addCriterion("driver_signature_time between", value1, value2, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignatureTimeNotBetween(Date value1, Date value2) {
            addCriterion("driver_signature_time not between", value1, value2, "driverSignatureTime");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathIsNull() {
            addCriterion("driver_signature_path is null");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathIsNotNull() {
            addCriterion("driver_signature_path is not null");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathEqualTo(String value) {
            addCriterion("driver_signature_path =", value, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathNotEqualTo(String value) {
            addCriterion("driver_signature_path <>", value, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathGreaterThan(String value) {
            addCriterion("driver_signature_path >", value, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathGreaterThanOrEqualTo(String value) {
            addCriterion("driver_signature_path >=", value, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathLessThan(String value) {
            addCriterion("driver_signature_path <", value, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathLessThanOrEqualTo(String value) {
            addCriterion("driver_signature_path <=", value, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathLike(String value) {
            addCriterion("driver_signature_path like", value, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathNotLike(String value) {
            addCriterion("driver_signature_path not like", value, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathIn(List<String> values) {
            addCriterion("driver_signature_path in", values, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathNotIn(List<String> values) {
            addCriterion("driver_signature_path not in", values, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathBetween(String value1, String value2) {
            addCriterion("driver_signature_path between", value1, value2, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andDriverSignaturePathNotBetween(String value1, String value2) {
            addCriterion("driver_signature_path not between", value1, value2, "driverSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusIsNull() {
            addCriterion("safer_confirm_status is null");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusIsNotNull() {
            addCriterion("safer_confirm_status is not null");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusEqualTo(String value) {
            addCriterion("safer_confirm_status =", value, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusNotEqualTo(String value) {
            addCriterion("safer_confirm_status <>", value, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusGreaterThan(String value) {
            addCriterion("safer_confirm_status >", value, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusGreaterThanOrEqualTo(String value) {
            addCriterion("safer_confirm_status >=", value, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusLessThan(String value) {
            addCriterion("safer_confirm_status <", value, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusLessThanOrEqualTo(String value) {
            addCriterion("safer_confirm_status <=", value, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusLike(String value) {
            addCriterion("safer_confirm_status like", value, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusNotLike(String value) {
            addCriterion("safer_confirm_status not like", value, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusIn(List<String> values) {
            addCriterion("safer_confirm_status in", values, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusNotIn(List<String> values) {
            addCriterion("safer_confirm_status not in", values, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusBetween(String value1, String value2) {
            addCriterion("safer_confirm_status between", value1, value2, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmStatusNotBetween(String value1, String value2) {
            addCriterion("safer_confirm_status not between", value1, value2, "saferConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeIsNull() {
            addCriterion("safer_confirm_time is null");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeIsNotNull() {
            addCriterion("safer_confirm_time is not null");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeEqualTo(Date value) {
            addCriterion("safer_confirm_time =", value, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeNotEqualTo(Date value) {
            addCriterion("safer_confirm_time <>", value, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeGreaterThan(Date value) {
            addCriterion("safer_confirm_time >", value, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("safer_confirm_time >=", value, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeLessThan(Date value) {
            addCriterion("safer_confirm_time <", value, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("safer_confirm_time <=", value, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeIn(List<Date> values) {
            addCriterion("safer_confirm_time in", values, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeNotIn(List<Date> values) {
            addCriterion("safer_confirm_time not in", values, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeBetween(Date value1, Date value2) {
            addCriterion("safer_confirm_time between", value1, value2, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferConfirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("safer_confirm_time not between", value1, value2, "saferConfirmTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusIsNull() {
            addCriterion("safer_signature_status is null");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusIsNotNull() {
            addCriterion("safer_signature_status is not null");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusEqualTo(String value) {
            addCriterion("safer_signature_status =", value, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusNotEqualTo(String value) {
            addCriterion("safer_signature_status <>", value, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusGreaterThan(String value) {
            addCriterion("safer_signature_status >", value, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusGreaterThanOrEqualTo(String value) {
            addCriterion("safer_signature_status >=", value, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusLessThan(String value) {
            addCriterion("safer_signature_status <", value, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusLessThanOrEqualTo(String value) {
            addCriterion("safer_signature_status <=", value, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusLike(String value) {
            addCriterion("safer_signature_status like", value, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusNotLike(String value) {
            addCriterion("safer_signature_status not like", value, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusIn(List<String> values) {
            addCriterion("safer_signature_status in", values, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusNotIn(List<String> values) {
            addCriterion("safer_signature_status not in", values, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusBetween(String value1, String value2) {
            addCriterion("safer_signature_status between", value1, value2, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureStatusNotBetween(String value1, String value2) {
            addCriterion("safer_signature_status not between", value1, value2, "saferSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeIsNull() {
            addCriterion("safer_signature_time is null");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeIsNotNull() {
            addCriterion("safer_signature_time is not null");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeEqualTo(Date value) {
            addCriterion("safer_signature_time =", value, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeNotEqualTo(Date value) {
            addCriterion("safer_signature_time <>", value, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeGreaterThan(Date value) {
            addCriterion("safer_signature_time >", value, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("safer_signature_time >=", value, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeLessThan(Date value) {
            addCriterion("safer_signature_time <", value, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeLessThanOrEqualTo(Date value) {
            addCriterion("safer_signature_time <=", value, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeIn(List<Date> values) {
            addCriterion("safer_signature_time in", values, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeNotIn(List<Date> values) {
            addCriterion("safer_signature_time not in", values, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeBetween(Date value1, Date value2) {
            addCriterion("safer_signature_time between", value1, value2, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignatureTimeNotBetween(Date value1, Date value2) {
            addCriterion("safer_signature_time not between", value1, value2, "saferSignatureTime");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathIsNull() {
            addCriterion("safer_signature_path is null");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathIsNotNull() {
            addCriterion("safer_signature_path is not null");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathEqualTo(String value) {
            addCriterion("safer_signature_path =", value, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathNotEqualTo(String value) {
            addCriterion("safer_signature_path <>", value, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathGreaterThan(String value) {
            addCriterion("safer_signature_path >", value, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathGreaterThanOrEqualTo(String value) {
            addCriterion("safer_signature_path >=", value, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathLessThan(String value) {
            addCriterion("safer_signature_path <", value, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathLessThanOrEqualTo(String value) {
            addCriterion("safer_signature_path <=", value, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathLike(String value) {
            addCriterion("safer_signature_path like", value, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathNotLike(String value) {
            addCriterion("safer_signature_path not like", value, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathIn(List<String> values) {
            addCriterion("safer_signature_path in", values, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathNotIn(List<String> values) {
            addCriterion("safer_signature_path not in", values, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathBetween(String value1, String value2) {
            addCriterion("safer_signature_path between", value1, value2, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andSaferSignaturePathNotBetween(String value1, String value2) {
            addCriterion("safer_signature_path not between", value1, value2, "saferSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusIsNull() {
            addCriterion("manufacturer_confirm_status is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusIsNotNull() {
            addCriterion("manufacturer_confirm_status is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusEqualTo(String value) {
            addCriterion("manufacturer_confirm_status =", value, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusNotEqualTo(String value) {
            addCriterion("manufacturer_confirm_status <>", value, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusGreaterThan(String value) {
            addCriterion("manufacturer_confirm_status >", value, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusGreaterThanOrEqualTo(String value) {
            addCriterion("manufacturer_confirm_status >=", value, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusLessThan(String value) {
            addCriterion("manufacturer_confirm_status <", value, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusLessThanOrEqualTo(String value) {
            addCriterion("manufacturer_confirm_status <=", value, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusLike(String value) {
            addCriterion("manufacturer_confirm_status like", value, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusNotLike(String value) {
            addCriterion("manufacturer_confirm_status not like", value, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusIn(List<String> values) {
            addCriterion("manufacturer_confirm_status in", values, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusNotIn(List<String> values) {
            addCriterion("manufacturer_confirm_status not in", values, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusBetween(String value1, String value2) {
            addCriterion("manufacturer_confirm_status between", value1, value2, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmStatusNotBetween(String value1, String value2) {
            addCriterion("manufacturer_confirm_status not between", value1, value2, "manufacturerConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeIsNull() {
            addCriterion("manufacturer_confirm_time is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeIsNotNull() {
            addCriterion("manufacturer_confirm_time is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeEqualTo(Date value) {
            addCriterion("manufacturer_confirm_time =", value, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeNotEqualTo(Date value) {
            addCriterion("manufacturer_confirm_time <>", value, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeGreaterThan(Date value) {
            addCriterion("manufacturer_confirm_time >", value, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("manufacturer_confirm_time >=", value, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeLessThan(Date value) {
            addCriterion("manufacturer_confirm_time <", value, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("manufacturer_confirm_time <=", value, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeIn(List<Date> values) {
            addCriterion("manufacturer_confirm_time in", values, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeNotIn(List<Date> values) {
            addCriterion("manufacturer_confirm_time not in", values, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeBetween(Date value1, Date value2) {
            addCriterion("manufacturer_confirm_time between", value1, value2, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerConfirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("manufacturer_confirm_time not between", value1, value2, "manufacturerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusIsNull() {
            addCriterion("manufacturer_signature_status is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusIsNotNull() {
            addCriterion("manufacturer_signature_status is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusEqualTo(String value) {
            addCriterion("manufacturer_signature_status =", value, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusNotEqualTo(String value) {
            addCriterion("manufacturer_signature_status <>", value, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusGreaterThan(String value) {
            addCriterion("manufacturer_signature_status >", value, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusGreaterThanOrEqualTo(String value) {
            addCriterion("manufacturer_signature_status >=", value, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusLessThan(String value) {
            addCriterion("manufacturer_signature_status <", value, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusLessThanOrEqualTo(String value) {
            addCriterion("manufacturer_signature_status <=", value, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusLike(String value) {
            addCriterion("manufacturer_signature_status like", value, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusNotLike(String value) {
            addCriterion("manufacturer_signature_status not like", value, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusIn(List<String> values) {
            addCriterion("manufacturer_signature_status in", values, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusNotIn(List<String> values) {
            addCriterion("manufacturer_signature_status not in", values, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusBetween(String value1, String value2) {
            addCriterion("manufacturer_signature_status between", value1, value2, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureStatusNotBetween(String value1, String value2) {
            addCriterion("manufacturer_signature_status not between", value1, value2, "manufacturerSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeIsNull() {
            addCriterion("manufacturer_signature_time is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeIsNotNull() {
            addCriterion("manufacturer_signature_time is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeEqualTo(Date value) {
            addCriterion("manufacturer_signature_time =", value, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeNotEqualTo(Date value) {
            addCriterion("manufacturer_signature_time <>", value, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeGreaterThan(Date value) {
            addCriterion("manufacturer_signature_time >", value, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("manufacturer_signature_time >=", value, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeLessThan(Date value) {
            addCriterion("manufacturer_signature_time <", value, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeLessThanOrEqualTo(Date value) {
            addCriterion("manufacturer_signature_time <=", value, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeIn(List<Date> values) {
            addCriterion("manufacturer_signature_time in", values, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeNotIn(List<Date> values) {
            addCriterion("manufacturer_signature_time not in", values, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeBetween(Date value1, Date value2) {
            addCriterion("manufacturer_signature_time between", value1, value2, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignatureTimeNotBetween(Date value1, Date value2) {
            addCriterion("manufacturer_signature_time not between", value1, value2, "manufacturerSignatureTime");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathIsNull() {
            addCriterion("manufacturer_signature_path is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathIsNotNull() {
            addCriterion("manufacturer_signature_path is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathEqualTo(String value) {
            addCriterion("manufacturer_signature_path =", value, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathNotEqualTo(String value) {
            addCriterion("manufacturer_signature_path <>", value, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathGreaterThan(String value) {
            addCriterion("manufacturer_signature_path >", value, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathGreaterThanOrEqualTo(String value) {
            addCriterion("manufacturer_signature_path >=", value, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathLessThan(String value) {
            addCriterion("manufacturer_signature_path <", value, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathLessThanOrEqualTo(String value) {
            addCriterion("manufacturer_signature_path <=", value, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathLike(String value) {
            addCriterion("manufacturer_signature_path like", value, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathNotLike(String value) {
            addCriterion("manufacturer_signature_path not like", value, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathIn(List<String> values) {
            addCriterion("manufacturer_signature_path in", values, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathNotIn(List<String> values) {
            addCriterion("manufacturer_signature_path not in", values, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathBetween(String value1, String value2) {
            addCriterion("manufacturer_signature_path between", value1, value2, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andManufacturerSignaturePathNotBetween(String value1, String value2) {
            addCriterion("manufacturer_signature_path not between", value1, value2, "manufacturerSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusIsNull() {
            addCriterion("consignee_confirm_status is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusIsNotNull() {
            addCriterion("consignee_confirm_status is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusEqualTo(String value) {
            addCriterion("consignee_confirm_status =", value, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusNotEqualTo(String value) {
            addCriterion("consignee_confirm_status <>", value, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusGreaterThan(String value) {
            addCriterion("consignee_confirm_status >", value, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusGreaterThanOrEqualTo(String value) {
            addCriterion("consignee_confirm_status >=", value, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusLessThan(String value) {
            addCriterion("consignee_confirm_status <", value, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusLessThanOrEqualTo(String value) {
            addCriterion("consignee_confirm_status <=", value, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusLike(String value) {
            addCriterion("consignee_confirm_status like", value, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusNotLike(String value) {
            addCriterion("consignee_confirm_status not like", value, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusIn(List<String> values) {
            addCriterion("consignee_confirm_status in", values, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusNotIn(List<String> values) {
            addCriterion("consignee_confirm_status not in", values, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusBetween(String value1, String value2) {
            addCriterion("consignee_confirm_status between", value1, value2, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmStatusNotBetween(String value1, String value2) {
            addCriterion("consignee_confirm_status not between", value1, value2, "consigneeConfirmStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeIsNull() {
            addCriterion("consignee_confirm_time is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeIsNotNull() {
            addCriterion("consignee_confirm_time is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeEqualTo(Date value) {
            addCriterion("consignee_confirm_time =", value, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeNotEqualTo(Date value) {
            addCriterion("consignee_confirm_time <>", value, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeGreaterThan(Date value) {
            addCriterion("consignee_confirm_time >", value, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("consignee_confirm_time >=", value, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeLessThan(Date value) {
            addCriterion("consignee_confirm_time <", value, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("consignee_confirm_time <=", value, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeIn(List<Date> values) {
            addCriterion("consignee_confirm_time in", values, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeNotIn(List<Date> values) {
            addCriterion("consignee_confirm_time not in", values, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeBetween(Date value1, Date value2) {
            addCriterion("consignee_confirm_time between", value1, value2, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeConfirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("consignee_confirm_time not between", value1, value2, "consigneeConfirmTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusIsNull() {
            addCriterion("consignee_signature_status is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusIsNotNull() {
            addCriterion("consignee_signature_status is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusEqualTo(String value) {
            addCriterion("consignee_signature_status =", value, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusNotEqualTo(String value) {
            addCriterion("consignee_signature_status <>", value, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusGreaterThan(String value) {
            addCriterion("consignee_signature_status >", value, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusGreaterThanOrEqualTo(String value) {
            addCriterion("consignee_signature_status >=", value, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusLessThan(String value) {
            addCriterion("consignee_signature_status <", value, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusLessThanOrEqualTo(String value) {
            addCriterion("consignee_signature_status <=", value, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusLike(String value) {
            addCriterion("consignee_signature_status like", value, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusNotLike(String value) {
            addCriterion("consignee_signature_status not like", value, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusIn(List<String> values) {
            addCriterion("consignee_signature_status in", values, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusNotIn(List<String> values) {
            addCriterion("consignee_signature_status not in", values, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusBetween(String value1, String value2) {
            addCriterion("consignee_signature_status between", value1, value2, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureStatusNotBetween(String value1, String value2) {
            addCriterion("consignee_signature_status not between", value1, value2, "consigneeSignatureStatus");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeIsNull() {
            addCriterion("consignee_signature_time is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeIsNotNull() {
            addCriterion("consignee_signature_time is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeEqualTo(Date value) {
            addCriterion("consignee_signature_time =", value, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeNotEqualTo(Date value) {
            addCriterion("consignee_signature_time <>", value, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeGreaterThan(Date value) {
            addCriterion("consignee_signature_time >", value, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("consignee_signature_time >=", value, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeLessThan(Date value) {
            addCriterion("consignee_signature_time <", value, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeLessThanOrEqualTo(Date value) {
            addCriterion("consignee_signature_time <=", value, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeIn(List<Date> values) {
            addCriterion("consignee_signature_time in", values, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeNotIn(List<Date> values) {
            addCriterion("consignee_signature_time not in", values, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeBetween(Date value1, Date value2) {
            addCriterion("consignee_signature_time between", value1, value2, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignatureTimeNotBetween(Date value1, Date value2) {
            addCriterion("consignee_signature_time not between", value1, value2, "consigneeSignatureTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathIsNull() {
            addCriterion("consignee_signature_path is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathIsNotNull() {
            addCriterion("consignee_signature_path is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathEqualTo(String value) {
            addCriterion("consignee_signature_path =", value, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathNotEqualTo(String value) {
            addCriterion("consignee_signature_path <>", value, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathGreaterThan(String value) {
            addCriterion("consignee_signature_path >", value, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathGreaterThanOrEqualTo(String value) {
            addCriterion("consignee_signature_path >=", value, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathLessThan(String value) {
            addCriterion("consignee_signature_path <", value, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathLessThanOrEqualTo(String value) {
            addCriterion("consignee_signature_path <=", value, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathLike(String value) {
            addCriterion("consignee_signature_path like", value, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathNotLike(String value) {
            addCriterion("consignee_signature_path not like", value, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathIn(List<String> values) {
            addCriterion("consignee_signature_path in", values, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathNotIn(List<String> values) {
            addCriterion("consignee_signature_path not in", values, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathBetween(String value1, String value2) {
            addCriterion("consignee_signature_path between", value1, value2, "consigneeSignaturePath");
            return (Criteria) this;
        }

        public Criteria andConsigneeSignaturePathNotBetween(String value1, String value2) {
            addCriterion("consignee_signature_path not between", value1, value2, "consigneeSignaturePath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_check_waybill
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 26 14:59:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Mon Mar 26 14:59:43 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}