package cm.cn.mapper;

import cm.cn.po.Gpsinfo;
import cm.cn.po.GpsinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GpsinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int countByExample(GpsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int deleteByExample(GpsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int deleteByPrimaryKey(Integer gpsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int insert(Gpsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int insertSelective(Gpsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    List<Gpsinfo> selectByExample(GpsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    Gpsinfo selectByPrimaryKey(Integer gpsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Gpsinfo record, @Param("example") GpsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int updateByExample(@Param("record") Gpsinfo record, @Param("example") GpsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int updateByPrimaryKeySelective(Gpsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo
     *
     * @mbggenerated Sat Feb 03 09:32:51 CST 2018
     */
    int updateByPrimaryKey(Gpsinfo record);
}