package cm.cn.mapper;

import cm.cn.po.HlCarAttach;
import cm.cn.po.HlCarAttachExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlCarAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int countByExample(HlCarAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int deleteByExample(HlCarAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int insert(HlCarAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int insertSelective(HlCarAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    List<HlCarAttach> selectByExample(HlCarAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    HlCarAttach selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") HlCarAttach record, @Param("example") HlCarAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int updateByExample(@Param("record") HlCarAttach record, @Param("example") HlCarAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int updateByPrimaryKeySelective(HlCarAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_car_attach
     *
     * @mbggenerated Tue Feb 27 12:49:58 CST 2018
     */
    int updateByPrimaryKey(HlCarAttach record);
}