package cm.cn.mapper;

import cm.cn.po.HlGoodsinfo;
import cm.cn.po.HlGoodsinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlGoodsinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int countByExample(HlGoodsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int deleteByExample(HlGoodsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int insert(HlGoodsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int insertSelective(HlGoodsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    List<HlGoodsinfo> selectByExample(HlGoodsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    HlGoodsinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") HlGoodsinfo record, @Param("example") HlGoodsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int updateByExample(@Param("record") HlGoodsinfo record, @Param("example") HlGoodsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int updateByPrimaryKeySelective(HlGoodsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_goodsinfo
     *
     * @mbggenerated Fri Feb 02 10:19:03 CST 2018
     */
    int updateByPrimaryKey(HlGoodsinfo record);
}