package cm.cn.mapper;

import cm.cn.po.HlSite;
import cm.cn.po.HlSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int countByExample(HlSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int deleteByExample(HlSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int insert(HlSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int insertSelective(HlSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    List<HlSite> selectByExample(HlSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    HlSite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") HlSite record, @Param("example") HlSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int updateByExample(@Param("record") HlSite record, @Param("example") HlSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int updateByPrimaryKeySelective(HlSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_site
     *
     * @mbggenerated Fri Mar 02 09:54:20 CST 2018
     */
    int updateByPrimaryKey(HlSite record);
}