package cm.cn.mapper;

import cm.cn.po.HlWaybillSite;
import cm.cn.po.HlWaybillSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlWaybillSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int countByExample(HlWaybillSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int deleteByExample(HlWaybillSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int insert(HlWaybillSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int insertSelective(HlWaybillSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    List<HlWaybillSite> selectByExample(HlWaybillSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    HlWaybillSite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") HlWaybillSite record, @Param("example") HlWaybillSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int updateByExample(@Param("record") HlWaybillSite record, @Param("example") HlWaybillSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int updateByPrimaryKeySelective(HlWaybillSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill_site
     *
     * @mbggenerated Fri Mar 02 16:06:19 CST 2018
     */
    int updateByPrimaryKey(HlWaybillSite record);
}