package cm.cn.mapper;

import cm.cn.po.HlCheckWaybill;
import cm.cn.po.HlCheckWaybillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlCheckWaybillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int countByExample(HlCheckWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int deleteByExample(HlCheckWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int insert(HlCheckWaybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int insertSelective(HlCheckWaybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    List<HlCheckWaybill> selectByExample(HlCheckWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    HlCheckWaybill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") HlCheckWaybill record, @Param("example") HlCheckWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int updateByExample(@Param("record") HlCheckWaybill record, @Param("example") HlCheckWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int updateByPrimaryKeySelective(HlCheckWaybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_check_waybill
     *
     * @mbggenerated Tue Mar 27 13:09:10 CST 2018
     */
    int updateByPrimaryKey(HlCheckWaybill record);
}