package cm.cn.mapper;

import cm.cn.po.HlMessage;
import cm.cn.po.HlMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int countByExample(HlMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int deleteByExample(HlMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int insert(HlMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int insertSelective(HlMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    List<HlMessage> selectByExample(HlMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    HlMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") HlMessage record, @Param("example") HlMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int updateByExample(@Param("record") HlMessage record, @Param("example") HlMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int updateByPrimaryKeySelective(HlMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_message
     *
     * @mbggenerated Fri Mar 30 15:07:39 CST 2018
     */
    int updateByPrimaryKey(HlMessage record);
}