package cm.cn.mapper;

import cm.cn.po.HlWaybill;
import cm.cn.po.HlWaybillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlWaybillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int countByExample(HlWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int deleteByExample(HlWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int insert(HlWaybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int insertSelective(HlWaybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    List<HlWaybill> selectByExample(HlWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    HlWaybill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") HlWaybill record, @Param("example") HlWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int updateByExample(@Param("record") HlWaybill record, @Param("example") HlWaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int updateByPrimaryKeySelective(HlWaybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_waybill
     *
     * @mbggenerated Thu Mar 29 14:49:02 CST 2018
     */
    int updateByPrimaryKey(HlWaybill record);
}